export const paths = {
  login: '/login',
  dashboard: '/dashboard',
  calendar: '/calendar',
  vehicles: '/vehicles',
  vehicleDetail: (id: string) => `/vehicles/${id}`,
  maintenance: '/maintenance',
  customers: '/customers',
  customerDetail: (id: string) => `/customers/${id}`,
  dispatchBoard: '/schedule/dispatch',
  employees: '/employees',
  employeeDetail: (id: string) => `/employees/${id}`,
  rentals: '/rentals',
  rentalDetail: (id: string) => `/rentals/${id}`,
  contracts: '/contracts',
  contractDetail: (id: string) => `/contracts/${id}`,
  handoverReturnTracking: '/handover-return',
  incidents: '/incidents',
  incidentDetail: (id: string) => `/incidents/${id}`,
  financeSettlement: '/finance/settlement',
  financeTransactions: '/finance/transactions',
  financeCashDrawer: '/finance/cash-drawer',
  financeReceivables: '/finance/receivables',
  financeReports: '/finance/reports',
  consignmentOwners: '/consignment/owners',
  consignmentContracts: '/consignment/contracts',
  consignmentPayouts: '/consignment/payouts',
  platformSystemConfig: '/platform/system-config',
  platformPermissions: '/platform/permissions',
  platformAudit: '/platform/audit',
  platformNotifications: '/platform/notifications',
} as const
